version: '3.7'

services:
  jekyll:
    image: bretfisher/jekyll-serve
    volumes:
      - .:/site
    ports:
      - '8000:4000'
    environment:
        - JEKYLL_GITHUB_TOKEN=${JEKYLL_GITHUB_TOKEN}
        - JEKYLL_BUILD_REVISION=${JEKYLL_BUILD_REVISION}
